### PR TITLE
Fix: Wrong type

### LINKED ISSUE #427: The option "scalar_types" with value array is expected to be of type "bool", but is of type "array".
I upgraded to version 3.0.0

#### Steps required to reproduce the problem

My config:
```php
<?php

declare(strict_types=1);

use Ergebnis\PhpCsFixer;

$config = PhpCsFixer\Config\Factory::fromRuleSet(new PhpCsFixer\Config\RuleSet\Php74(''), [
    'php_unit_internal_class' => false,
]);

$config->getFinder()
    ->in('build')
    ->in('migrations')
    ->in('src')
    ->in('tests')
    ->in('tools')
;

$config->setCacheFile(__DIR__ . '/.build/php-cs-fixer/.php-cs-fixer.cache');

return $config;

```

#### Expected Result

* No error

#### Actual Result

For readability:
CleanShot 2021-05-05 at 08 09 30@2x

As text:
```
symfony php vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php --diff --verbose
PHP CS Fixer 3.0.0 Constitution by Fabien Potencier and Dariusz Ruminski
Runtime: PHP 8.0.3
Loaded config ergebnis (PHP 7.4) from ".php-cs-fixer.dist.php".

In AbstractFixer.php line 155:

  [PhpCsFixer\ConfigurationException\InvalidFixerConfigurationException (32)]
  [phpdoc_to_property_type] Invalid configuration: The option "scalar_types" with value array is expected to be of type "bool", but is of type "array".


Exception trace:
  at /Users/oskar.stark/dev/datana/cockpit/vendor/friendsofphp/php-cs-fixer/src/AbstractFixer.php:155
 PhpCsFixer\AbstractFixer->configure() at /Users/oskar.stark/dev/datana/cockpit/vendor/friendsofphp/php-cs-fixer/src/FixerFactory.php:169
 PhpCsFixer\FixerFactory->useRuleSet() at /Users/oskar.stark/dev/datana/cockpit/vendor/friendsofphp/php-cs-fixer/src/Console/ConfigurationResolver.php:292
 PhpCsFixer\Console\ConfigurationResolver->getFixers() at /Users/oskar.stark/dev/datana/cockpit/vendor/friendsofphp/php-cs-fixer/src/Console/Command/FixCommand.php:306
 PhpCsFixer\Console\Command\FixCommand->execute() at /Users/oskar.stark/dev/datana/cockpit/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /Users/oskar.stark/dev/datana/cockpit/vendor/symfony/console/Application.php:971
 Symfony\Component\Console\Application->doRunCommand() at /Users/oskar.stark/dev/datana/cockpit/vendor/symfony/console/Application.php:290
 Symfony\Component\Console\Application->doRun() at /Users/oskar.stark/dev/datana/cockpit/vendor/friendsofphp/php-cs-fixer/src/Console/Application.php:97
 PhpCsFixer\Console\Application->doRun() at /Users/oskar.stark/dev/datana/cockpit/vendor/symfony/console/Application.php:166
 Symfony\Component\Console\Application->run() at /Users/oskar.stark/dev/datana/cockpit/vendor/friendsofphp/php-cs-fixer/php-cs-fixer:113

In OptionsResolver.php line 1030:

  [Symfony\Component\OptionsResolver\Exception\InvalidOptionsException]
  The option "scalar_types" with value array is expected to be of type "bool", but is of type "array".


Exception trace:
  at /Users/oskar.stark/dev/datana/cockpit/vendor/symfony/options-resolver/OptionsResolver.php:1030
 Symfony\Component\OptionsResolver\OptionsResolver->offsetGet() at /Users/oskar.stark/dev/datana/cockpit/vendor/symfony/options-resolver/OptionsResolver.php:910
 Symfony\Component\OptionsResolver\OptionsResolver->resolve() at /Users/oskar.stark/dev/datana/cockpit/vendor/friendsofphp/php-cs-fixer/src/FixerConfiguration/FixerConfigurationResolver.php:110
 PhpCsFixer\FixerConfiguration\FixerConfigurationResolver->resolve() at /Users/oskar.stark/dev/datana/cockpit/vendor/friendsofphp/php-cs-fixer/src/AbstractFixer.php:141
 PhpCsFixer\AbstractFixer->configure() at /Users/oskar.stark/dev/datana/cockpit/vendor/friendsofphp/php-cs-fixer/src/FixerFactory.php:169
 PhpCsFixer\FixerFactory->useRuleSet() at /Users/oskar.stark/dev/datana/cockpit/vendor/friendsofphp/php-cs-fixer/src/Console/ConfigurationResolver.php:292
 PhpCsFixer\Console\ConfigurationResolver->getFixers() at /Users/oskar.stark/dev/datana/cockpit/vendor/friendsofphp/php-cs-fixer/src/Console/Command/FixCommand.php:306
 PhpCsFixer\Console\Command\FixCommand->execute() at /Users/oskar.stark/dev/datana/cockpit/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /Users/oskar.stark/dev/datana/cockpit/vendor/symfony/console/Application.php:971
 Symfony\Component\Console\Application->doRunCommand() at /Users/oskar.stark/dev/datana/cockpit/vendor/symfony/console/Application.php:290
 Symfony\Component\Console\Application->doRun() at /Users/oskar.stark/dev/datana/cockpit/vendor/friendsofphp/php-cs-fixer/src/Console/Application.php:97
 PhpCsFixer\Console\Application->doRun() at /Users/oskar.stark/dev/datana/cockpit/vendor/symfony/console/Application.php:166
 Symfony\Component\Console\Application->run() at /Users/oskar.stark/dev/datana/cockpit/vendor/friendsofphp/php-cs-fixer/php-cs-fixer:113

fix [--path-mode PATH-MODE] [--allow-risky ALLOW-RISKY] [--config CONFIG] [--dry-run] [--rules RULES] [--using-cache USING-CACHE] [--cache-file CACHE-FILE] [--diff] [--format FORMAT] [--stop-on-violation] [--show-progress SHOW-PROGRESS] [--] [<path>...]

exit status 32
```

### PR DESCRIPTION
**Pull request by OskarStark**
This pull request

* [x] fixes `The option "scalar_types" with value array is expected to be of type "bool", but is of type "array". `

Fixes #427.

### CODE REVIEW

File: src/RuleSet/Php74.php [hunk 1]
```diff
@@ -892,9 +892,7 @@ final class Php74 extends AbstractRuleSet implements ExplicitRuleSet
         'phpdoc_to_comment' => false,
         'phpdoc_to_param_type' => false,
         'phpdoc_to_property_type' => [
-            'scalar_types' => [
-                'bool',
-            ],
+            'scalar_types' => false,
```
Comment (OskarStark) [inline src/RuleSet/Php74.php:895]: Not sure you want to have `true` or `false` here @localheinz

**Review by localheinz — APPROVED** [review]
👍

**Comment by localheinz** [comment]
Thank you, @OskarStark!
